/// Brief one-line description for well-known ATA SMART attribute IDs.
pub fn describe(id: u32) -> Option<&'static str> {
    Some(match id {
        1   => "Raw Read Error Rate — read errors from disk surface; high raw value normal on Seagate/WD",
        3   => "Spin-Up Time — milliseconds to reach full RPM from stopped",
        4   => "Start/Stop Count — total motor start/stop cycles since manufacture",
        5   => "Reallocated Sectors — bad sectors remapped to spare pool; any increase is a warning",
        7   => "Seek Error Rate — head seek errors; high raw value is normal on Seagate",
        8   => "Seek Time Performance — efficiency of seek operations (higher=better)",
        9   => "Power-On Hours — cumulative hours the drive has been powered on",
        10  => "Spin Retry Count — failed attempts to spin up; non-zero indicates mechanical problems",
        11  => "Recalibration Retries — head recalibration failures; should stay at 0",
        12  => "Power Cycle Count — times the drive has been powered on from off",
        183 => "SATA Downshift Count — SATA interface speed downgrades due to errors; check cable",
        184 => "End-to-End Error — data corruption between host buffer and disk buffer",
        187 => "Reported Uncorrectable Errors — errors that ECC could not fix; critical warning",
        188 => "Command Timeout — commands aborted due to timeout; should be 0",
        190 => "Airflow Temperature — temperature measured at drive housing",
        191 => "G-Sense Error Rate — mechanical shock / vibration events recorded",
        192 => "Power-Off Retract Count — emergency head retracts due to sudden power loss",
        193 => "Load/Unload Cycles — park/load cycles; typical HDD limit ~600,000",
        194 => "Temperature — drive internal temperature in Celsius (raw value)",
        195 => "Hardware ECC Recovered — read errors corrected on-the-fly; non-zero is OK",
        196 => "Reallocation Event Count — total reallocations attempted (not all succeeded)",
        197 => "Pending Sectors — unstable sectors awaiting reallocation; critical indicator",
        198 => "Uncorrectable Sectors — sectors that failed reallocation; critical indicator",
        199 => "UltraDMA CRC Errors — SATA data corruption; bad cable or connector",
        200 => "Write Error Rate — errors during write operations",
        206 => "Flying Height — distance between head and platter surface",
        220 => "Disk Shift — physical shift of disk platter due to shock",
        241 => "Total LBAs Written — total data written to drive since manufacture",
        242 => "Total LBAs Read — total data read from drive since manufacture",
        254 => "Free Fall Protection — free-fall sensor trigger count",
        _   => return None,
    })
}
